# This is a basic workflow to help you get started with Actions

name: Build_VIPM_Library

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches:
      - main
    types: [closed]

  push:
    paths-ignore:
      - '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build_VIPM_Library:
    # The type of runner that the job will run on
    runs-on: [self-hosted, lv2014]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Get env variables
      # https://github.com/marketplace/actions/github-environment-variables-action
      - uses: FranzDiebold/github-env-vars-action@v2

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: BuildDailyVIP
        id: build-vip
        uses: NEVSTOP-LAB/vipm-BuildViPackage@main
        with:
          LabVIEW_Version: 2014
          VipbPath: ${{ github.workspace }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          # Artifact name
          name: ${{ steps.build-vip.outputs.vipName }}
          path: ${{ steps.build-vip.outputs.vipPathName }}
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: warn
          retention-days: 90

      # Backup generated files by ftp
      # https://github.com/marketplace/actions/simple-ftp-upload
      - name: backup Build Artifact by ftp
        uses: dennisameling/ftp-upload-action@v1.0.9
        with:
          server: ${{ secrets.VIPM_FTP_IP }}
          port: ${{ secrets.VIPM_FTP_PORT }}
          username: ${{ secrets.VIPM_FTP_USER }}
          password: ${{ secrets.VIPM_FTP_PASSWORD }}
          secure: false
          server_dir: /${{ env.CI_REPOSITORY_OWNER_SLUG }}/${{ env.CI_REPOSITORY_NAME }}/${{ env.CI_ACTION_REF_NAME }}/
          local_dir: ./vip/
